version: '3.8'

services:
  conectisp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./nginx_logs:/var/log/nginx
    restart: unless-stopped